stages:
  - build
  - test

image: gcc:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
before_script:
  - apt-get update
  - apt-get install -y docker.io

build_task1:
  stage: build
  script:
    - echo "task one running"
    - docker build -t simulation:1 .
    - docker save simulation:1 > simulation_task1.tar
    - echo "Contents of /scratch before running container:" # Debugging
    - ls -l $CI_PROJECT_DIR/scratch # Debugging
    #- docker run --rm simulation:1
    #- docker run --rm -v $CI_PROJECT_DIR/simulation/disease_in.ini:/scratch/simulation/disease_in.ini simulation:1
    - docker run --rm -v /simulation/disease_in.ini:/scratch/simulation/disease_in.ini simulation:1
    - echo "finished running simulation task 1"
  artifacts:
    paths:
      - simulation_task1.tar
    expire_in: 1 day
  timeout: 2h 

test_task1:
  stage: test
  script:
    - echo "Running tests for task one"
    - g++ -o test_simulation simulation/test.cpp simulation/simulation.cpp -I simulation/
    - cp simulation/disease_in.ini .
    - ./test_simulation
  artifacts:
    paths:
      - test_simulation
    expire_in: 1 day #fixed aftr 2 days

build_task2:
  stage: build
  script:
    - echo "task two running"
    - cd simulation/'task two'
    - docker build -t simulation:2 .
    - docker save simulation:2 > simulation_task2.tar
    - docker run --rm simulation:2
    - echo "finished running simulation task 2"
  artifacts:
    paths:
      - simulation/task two/simulation_task2.tar
    expire_in: 1 day
  timeout: 2h

