stages:
  - build

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t simulation .
    - docker save simulation > simulation.tar
  artifacts:
    paths:
      - simulation.tar
    expire_in: 1 week
