stages:
  - build
  - test
  # - deploy

image: 
  name: docker:latest
  name: gcc:13.3

services:
  - docker:dind
  - gcc

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info
  - gcc --version

build_task1:
  stage: build
  # tags:
  #   - simulation-one
  script:
    - echo "task one running"
    - docker build -t simulation:1 .
    - docker save simulation:1 > simulation_task1.tar
    - docker run --rm simulation:1
    - echo "finished running simulation task 1"
  artifacts:
    paths:
      - simulation_task1.tar
    expire_in: 1 week
  timeout: 2h  # Increase timeout to 2 hours

test_task1:
  stage: test
  script:
    - echo "Running tests for task one"
    - g++ -o test_simulation test.cpp simulation.cpp
    - ./test_simulation


build_task2:
  stage: build
  # tags:
  #   - simulation-two
  script:
    - echo "task two running"
    - cd simulation/'task two'
    - docker build -t simulation:2 .
    - docker save simulation:2 > simulation_task2.tar
    - docker run --rm simulation:2
    - echo "finished running simulation task 2"
  artifacts:
    paths:
      - simulation/task two/simulation_task2.tar
    expire_in: 1 week
  timeout: 2h  # Increase timeout to 2 hours

# test_task2:
#   stage: test
#   tags:
#     - simulation-tag
#   script:
#     - cd tasktwo
#     - docker load -i simulation_task2.tar
#     - docker run simulation:2 ./run_tests.sh
#   dependencies:
#     - build_task2

# deploy:
#   stage: deploy
#   tags:
#     - simulation-tag
#   script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
#     - docker tag simulation:1 $CI_REGISTRY/sh04625/hpc-disease-simulation/:simulation1
#     - docker tag simulation:2 $CI_REGISTRY/sh04625/hpc-disease-simulation/:simulation2
#     - docker push $CI_REGISTRY/sh04625/hpc-disease-simulation/:simulation1
#     - docker push $CI_REGISTRY/sh04625/hpc-disease-simulation/:simulation2
#   only:
#     - main

# nightly_build:
#   stage: build
#   tags:
#     - simulation-tag
#   script:
#     - docker build -t simulation:nightly .
#     - docker tag simulation:nightly $CI_REGISTRY/your-username/your-repository:nightly
#     - docker push $CI_REGISTRY/sh04625/hpc-disease-simulation/:nightly
#   only:
#     - schedules
