stages:
  - build

image: docker:latest 

build:
  stage: build
  script:
    - docker build -t B simulation .#ui
  triggers:
    schedule:
      cron: "0 0 * * *"
  

  artifacts:
    paths:
      - docker-images/simulation.tar      
      
   
